# Generated by Django 2.2.5 on 2019-09-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
