# Generated by Django 2.2.5 on 2019-09-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190910_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizappuser',
            name='profile_image',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
